# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@polka/url-0.5.0" = {
      name = "_at_polka_slash_url";
      packageName = "@polka/url";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@polka/url/-/url-0.5.0.tgz";
        sha512 = "oZLYFEAzUKyi3SKnXvj32ZCEGH6RDnao7COuCVhDydMS9NrCSVXhM79VaKyP5+Zc33m0QXEd2DN3UkU7OsHcfw==";
      };
    };
    "@types/color-name-1.1.1" = {
      name = "_at_types_slash_color-name";
      packageName = "@types/color-name";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/color-name/-/color-name-1.1.1.tgz";
        sha512 = "rr+OQyAjxze7GgWrSaJwydHStIhHq2lvY3BOC2Mj7KnzI7XK0Uw1TOOdI9lDoajEbSWLiYgoo4f1R51erQfhPQ==";
      };
    };
    "@types/q-1.5.4" = {
      name = "_at_types_slash_q";
      packageName = "@types/q";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/q/-/q-1.5.4.tgz";
        sha512 = "1HcDas8SEj4z1Wc696tH56G8OlRaH/sqZOynNNB+HF0WOeXPaxTtbYzJY2oEfiUxjSKjhCKr+MvR7dCHcEelug==";
      };
    };
    "alphanum-sort-1.0.2" = {
      name = "alphanum-sort";
      packageName = "alphanum-sort";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alphanum-sort/-/alphanum-sort-1.0.2.tgz";
        sha1 = "97a1119649b211ad33691d9f9f486a8ec9fbe0a3";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.2.1.tgz";
        sha512 = "9VGjrMsG1vePxcSweQsN20KY/c4zN0h9fLjqAbwbPfahM3t+NL+M9HC8xeXG2I8pX5NoamTGNuomEUFI7fcUjA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "big.js-5.2.2" = {
      name = "big.js";
      packageName = "big.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-5.2.2.tgz";
        sha512 = "vyL2OymJxmarO8gxMr0mhChsO9QGwhynfuu4+MHTAW6czfq9humCB7rKpUjDd9YUiDPU4mzpyupFSvOClAwbmQ==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "bootstrap-4.5.0" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.5.0.tgz";
        sha512 = "Z93QoXvodoVslA+PWNdk23Hze4RBYIkpb5h8I2HY2Tu2h7A0LpAgLcyrhrSUyo2/Oxm2l1fRZPs1e5hnxnliXA==";
      };
    };
    "browserslist-4.12.0" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.12.0.tgz";
        sha512 = "UH2GkcEDSI0k/lRkuDSzFl9ZZ87skSy9w2XAn1MsZnL+4c4rqbBd3e82UWHbYDpztABrPBhZsTEeuxVfHppqDg==";
      };
    };
    "caller-callsite-2.0.0" = {
      name = "caller-callsite";
      packageName = "caller-callsite";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-callsite/-/caller-callsite-2.0.0.tgz";
        sha1 = "847e0fce0a223750a9a027c54b33731ad3154134";
      };
    };
    "caller-path-2.0.0" = {
      name = "caller-path";
      packageName = "caller-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caller-path/-/caller-path-2.0.0.tgz";
        sha1 = "468f83044e369ab2010fac5f06ceee15bb2cb1f4";
      };
    };
    "callsites-2.0.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-2.0.0.tgz";
        sha1 = "06eb84f00eea413da86affefacbffb36093b3c50";
      };
    };
    "caniuse-api-3.0.0" = {
      name = "caniuse-api";
      packageName = "caniuse-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-api/-/caniuse-api-3.0.0.tgz";
        sha512 = "bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==";
      };
    };
    "caniuse-lite-1.0.30001084" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001084";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001084.tgz";
        sha512 = "ftdc5oGmhEbLUuMZ/Qp3mOpzfZLCxPYKcvGv6v2dJJ+8EdqcvZRbAGOiLmkM/PV1QGta/uwBs8/nCl6sokDW6w==";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz";
        sha512 = "qwx12AxXe2Q5xQ43Ac//I6v5aXTipYrSESdOgzrN+9XjgEpyjpKuvSGaN4qE93f7TQTlerQQ8S+EQ0EyDoVL1A==";
      };
    };
    "coa-2.0.2" = {
      name = "coa";
      packageName = "coa";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/coa/-/coa-2.0.2.tgz";
        sha512 = "q5/jG+YQnSy4nRTV4F7lPepBJZ8qBNJJDBuJdoejDyLXgmL7IEo+Le2JDZudFTFt7mrCqIRaSjws4ygRCTCAXA==";
      };
    };
    "color-3.1.2" = {
      name = "color";
      packageName = "color";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color/-/color-3.1.2.tgz";
        sha512 = "vXTJhHebByxZn3lDvDJYw4lR5+uB3vuoHsuYA5AKuxRVn5wzzIfQKGLBmgdVRHKTJYeK5rvJcHnrd0Li49CFpg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "color-string-1.5.3" = {
      name = "color-string";
      packageName = "color-string";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-string/-/color-string-1.5.3.tgz";
        sha512 = "dC2C5qeWoYkxki5UAXapdjqO672AM4vZuPGRQfO8b5HKuKGBbKWpITyDYN7TOFKvRW7kOgAn3746clDBMDJyQw==";
      };
    };
    "concat-with-sourcemaps-1.1.0" = {
      name = "concat-with-sourcemaps";
      packageName = "concat-with-sourcemaps";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-with-sourcemaps/-/concat-with-sourcemaps-1.1.0.tgz";
        sha512 = "4gEjHJFT9e+2W/77h/DS5SGUgwDaOwprX8L/gl5+3ixnzkVJJsZWDSelmN3Oilw3LNDZjZV0yqH1hLG3k6nghg==";
      };
    };
    "console-clear-1.1.1" = {
      name = "console-clear";
      packageName = "console-clear";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-clear/-/console-clear-1.1.1.tgz";
        sha512 = "pMD+MVR538ipqkG5JXeOEbKWS5um1H4LUUccUQG68qpeqBYbzYy79Gh55jkd2TtPdRfUaLWdv6LPP//5Zt0aPQ==";
      };
    };
    "cosmiconfig-5.2.1" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-5.2.1.tgz";
        sha512 = "H65gsXo1SKjf8zmrJ67eJk8aIRKV5ff2D4uKZIBZShbhGSpEmsQOPW/SKMKYhSTrqR7ufy6RP69rPogdaPh/kA==";
      };
    };
    "css-color-names-0.0.4" = {
      name = "css-color-names";
      packageName = "css-color-names";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-color-names/-/css-color-names-0.0.4.tgz";
        sha1 = "808adc2e79cf84738069b646cb20ec27beb629e0";
      };
    };
    "css-declaration-sorter-4.0.1" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-4.0.1.tgz";
        sha512 = "BcxQSKTSEEQUftYpBVnsH4SF05NTuBokb19/sBt6asXGKZ/6VP7PLG1CBCkFDYOnhXhPh0jMhO6xZ71oYHXHBA==";
      };
    };
    "css-modules-loader-core-1.1.0" = {
      name = "css-modules-loader-core";
      packageName = "css-modules-loader-core";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-modules-loader-core/-/css-modules-loader-core-1.1.0.tgz";
        sha1 = "5908668294a1becd261ae0a4ce21b0b551f21d16";
      };
    };
    "css-select-2.1.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-2.1.0.tgz";
        sha512 = "Dqk7LQKpwLoH3VovzZnkzegqNSuAziQyNZUcrdDM401iY+R5NkGBXGmtO05/yaXQziALuPogeG0b7UAgjnTJTQ==";
      };
    };
    "css-select-base-adapter-0.1.1" = {
      name = "css-select-base-adapter";
      packageName = "css-select-base-adapter";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select-base-adapter/-/css-select-base-adapter-0.1.1.tgz";
        sha512 = "jQVeeRG70QI08vSTwf1jHxp74JoZsr2XSgETae8/xC8ovSnL2WF87GTLO86Sbwdt2lK4Umg4HnnwMO4YF3Ce7w==";
      };
    };
    "css-selector-tokenizer-0.7.2" = {
      name = "css-selector-tokenizer";
      packageName = "css-selector-tokenizer";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-selector-tokenizer/-/css-selector-tokenizer-0.7.2.tgz";
        sha512 = "yj856NGuAymN6r8bn8/Jl46pR+OC3eEvAhfGYDUe7YPtTPAYrSSw4oAniZ9Y8T5B92hjhwTBLUen0/vKPxf6pw==";
      };
    };
    "css-tree-1.0.0-alpha.37" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.0.0-alpha.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.37.tgz";
        sha512 = "DMxWJg0rnz7UgxKT0Q1HU/L9BeJI0M6ksor0OgqOnF+aRCDWg/N2641HmVyU9KVIu0OVVWOb2IpC9A+BJRnejg==";
      };
    };
    "css-tree-1.0.0-alpha.39" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.0.0-alpha.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.39.tgz";
        sha512 = "7UvkEYgBAHRG9Nt980lYxjsTrCyHFN53ky3wVsDkiMdVqylqRt+Zc+jm5qw7/qyOvN2dHSYtX0e4MbCCExSvnA==";
      };
    };
    "css-what-3.3.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-3.3.0.tgz";
        sha512 = "pv9JPyatiPaQ6pf4OvD/dbfm0o5LviWmwxNWzblYf/1u9QZd0ihV+PMwy5jdQWQ3349kZmKEx9WXuSka2dM4cg==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "cssnano-4.1.10" = {
      name = "cssnano";
      packageName = "cssnano";
      version = "4.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano/-/cssnano-4.1.10.tgz";
        sha512 = "5wny+F6H4/8RgNlaqab4ktc3e0/blKutmq8yNlBFXA//nSFFAqAngjNVRzUvCgYROULmZZUoosL/KSoZo5aUaQ==";
      };
    };
    "cssnano-preset-default-4.0.7" = {
      name = "cssnano-preset-default";
      packageName = "cssnano-preset-default";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-4.0.7.tgz";
        sha512 = "x0YHHx2h6p0fCl1zY9L9roD7rnlltugGu7zXSKQx6k2rYw0Hi3IqxcoAGF7u9Q5w1nt7vK0ulxV8Lo+EvllGsA==";
      };
    };
    "cssnano-util-get-arguments-4.0.0" = {
      name = "cssnano-util-get-arguments";
      packageName = "cssnano-util-get-arguments";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-arguments/-/cssnano-util-get-arguments-4.0.0.tgz";
        sha1 = "ed3a08299f21d75741b20f3b81f194ed49cc150f";
      };
    };
    "cssnano-util-get-match-4.0.0" = {
      name = "cssnano-util-get-match";
      packageName = "cssnano-util-get-match";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-get-match/-/cssnano-util-get-match-4.0.0.tgz";
        sha1 = "c0e4ca07f5386bb17ec5e52250b4f5961365156d";
      };
    };
    "cssnano-util-raw-cache-4.0.1" = {
      name = "cssnano-util-raw-cache";
      packageName = "cssnano-util-raw-cache";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-raw-cache/-/cssnano-util-raw-cache-4.0.1.tgz";
        sha512 = "qLuYtWK2b2Dy55I8ZX3ky1Z16WYsx544Q0UWViebptpwn/xDBmog2TLg4f+DBMg1rJ6JDWtn96WHbOKDWt1WQA==";
      };
    };
    "cssnano-util-same-parent-4.0.1" = {
      name = "cssnano-util-same-parent";
      packageName = "cssnano-util-same-parent";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-util-same-parent/-/cssnano-util-same-parent-4.0.1.tgz";
        sha512 = "WcKx5OY+KoSIAxBW6UBBRay1U6vkYheCdjyVNDm85zt5K9mHoGOfsOsqIszfAqrQQFIIKgjh2+FDgIj/zsl21Q==";
      };
    };
    "csso-4.0.3" = {
      name = "csso";
      packageName = "csso";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-4.0.3.tgz";
        sha512 = "NL3spysxUkcrOgnpsT4Xdl2aiEiBG6bXswAABQVHcMrfjjBisFOKwLDOmf4wf32aPdcJws1zds2B0Rg+jqMyHQ==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "dot-prop-5.2.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-5.2.0.tgz";
        sha512 = "uEUyaDKoSQ1M4Oq8l45hSE26SnTxL6snNnqvK/VWx5wJhmff5z0FUVJDKDanor/6w3kzE3i7XZOk+7wC0EXr1A==";
      };
    };
    "electron-to-chromium-1.3.477" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.3.477";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.477.tgz";
        sha512 = "81p6DZ/XmHDD7O0ITJMa7ESo9bSCfE+v3Fny3MIYR0y77xmhoriu2ShNOLXcPS4eowF6dkxw6d2QqxTkS3DjBg==";
      };
    };
    "emojis-list-3.0.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz";
        sha512 = "/kyM18EfinwXZbno9FyUGeFh87KC8HRQBQGildHZbEuRyWFOmv1U10o9BBp8XVZDVNNuQKyIGIu5ZYAAXJ0V2Q==";
      };
    };
    "entities-2.0.3" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.3.tgz";
        sha512 = "MyoZ0jgnLvB2X3Lg5HqpFmn1kybDiIfEQmKzTb5apr51Rb+T3KdmMiqa70T+bhGnyv7bQ6WMj2QMHpGMmlrUYQ==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es-abstract-1.17.6" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.6.tgz";
        sha512 = "Fr89bON3WFyUi5EvAeI48QTWX0AyekGgLA8H+c+7fbfCkJwRWRMLd8CQedNEyJuoYYhmtEqY92pgte1FAhBlhw==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "estree-walker-0.6.1" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-0.6.1.tgz";
        sha512 = "SqmZANLWS0mnatqbSfRP5g8OXZC12Fgg1IwNtLsyHDzJizORW4khDfjPqJZsemPWBB2uqykUah5YpQ6epsqC/w==";
      };
    };
    "eventemitter3-4.0.4" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.4.tgz";
        sha512 = "rlaVLnVxtxvoyLsQQFBx53YmXHDxRIzzTLbdfxqi4yocpSjAxXwkU0cScM5JgSKMqEhrZpnvQ2D9gjylR0AimQ==";
      };
    };
    "fastparse-1.1.2" = {
      name = "fastparse";
      packageName = "fastparse";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastparse/-/fastparse-1.1.2.tgz";
        sha512 = "483XLLxTVIwWK3QTrMGRqUfUpoOs/0hbQrl2oz4J0pAcm3A3bu84wxTFqGqkJzewCLdME38xJLJAxBABfQT8sQ==";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "generic-names-2.0.1" = {
      name = "generic-names";
      packageName = "generic-names";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-names/-/generic-names-2.0.1.tgz";
        sha512 = "kPCHWa1m9wGG/OwQpeweTwM/PYiQLrUIxXbt/P4Nic3LbGjCP0YwrALHW1uNLKZ0LIMg+RF+XRlj2ekT9ZlZAQ==";
      };
    };
    "get-port-3.2.0" = {
      name = "get-port";
      packageName = "get-port";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-port/-/get-port-3.2.0.tgz";
        sha1 = "dd7ce7de187c06c8bf353796ac71e099f0980ebc";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-1.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-1.0.0.tgz";
        sha1 = "9d9e793165ce017a00f00418c43f942a7b1d11fa";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "hex-color-regex-1.1.0" = {
      name = "hex-color-regex";
      packageName = "hex-color-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hex-color-regex/-/hex-color-regex-1.1.0.tgz";
        sha512 = "l9sfDFsuqtOqKDsQdqrMRk0U85RZc0RtOR9yPI7mRVOa4FsR/BVnZ0shmQRM96Ji99kYZP/7hn1cedc1+ApsTQ==";
      };
    };
    "hsl-regex-1.0.0" = {
      name = "hsl-regex";
      packageName = "hsl-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsl-regex/-/hsl-regex-1.0.0.tgz";
        sha1 = "d49330c789ed819e276a4c0d272dffa30b18fe6e";
      };
    };
    "hsla-regex-1.0.0" = {
      name = "hsla-regex";
      packageName = "hsla-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsla-regex/-/hsla-regex-1.0.0.tgz";
        sha1 = "c1ce7a3168c8c6614033a4b5f7877f3b225f9c38";
      };
    };
    "html-comment-regex-1.1.2" = {
      name = "html-comment-regex";
      packageName = "html-comment-regex";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-comment-regex/-/html-comment-regex-1.1.2.tgz";
        sha512 = "P+M65QY2JQ5Y0G9KKdlDpo0zK+/OHptU5AaBwUfAIDJZk1MYf32Frm84EcOytfJE0t5JvkAnKlmjsXDnWzCJmQ==";
      };
    };
    "icss-replace-symbols-1.1.0" = {
      name = "icss-replace-symbols";
      packageName = "icss-replace-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-replace-symbols/-/icss-replace-symbols-1.1.0.tgz";
        sha1 = "06ea6f83679a7749e386cfe1fe812ae5db223ded";
      };
    };
    "import-cwd-2.1.0" = {
      name = "import-cwd";
      packageName = "import-cwd";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-cwd/-/import-cwd-2.1.0.tgz";
        sha1 = "aa6cf36e722761285cb371ec6519f53e2435b0a9";
      };
    };
    "import-cwd-3.0.0" = {
      name = "import-cwd";
      packageName = "import-cwd";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-cwd/-/import-cwd-3.0.0.tgz";
        sha512 = "4pnzH16plW+hgvRECbDWpQl3cqtvSofHWh44met7ESfZ8UZOWWddm8hEyDTqREJ9RbYHY8gi8DqmaelApoOGMg==";
      };
    };
    "import-fresh-2.0.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-2.0.0.tgz";
        sha1 = "d81355c15612d386c61f9ddd3922d4304822a546";
      };
    };
    "import-from-2.1.0" = {
      name = "import-from";
      packageName = "import-from";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-from/-/import-from-2.1.0.tgz";
        sha1 = "335db7f2a7affd53aaa471d4b8021dee36b7f3b1";
      };
    };
    "import-from-3.0.0" = {
      name = "import-from";
      packageName = "import-from";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-from/-/import-from-3.0.0.tgz";
        sha512 = "CiuXOFFSzkU5x/CR0+z7T91Iht4CXgfCxVOFRhh2Zyhg5wOpWvvDLQUsWl+gcN+QscYBjez8hDCt85O7RLDttQ==";
      };
    };
    "indexes-of-1.0.1" = {
      name = "indexes-of";
      packageName = "indexes-of";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexes-of/-/indexes-of-1.0.1.tgz";
        sha1 = "f30f716c8e2bd346c7b67d3df3915566a7c05607";
      };
    };
    "is-absolute-url-2.1.0" = {
      name = "is-absolute-url";
      packageName = "is-absolute-url";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute-url/-/is-absolute-url-2.1.0.tgz";
        sha1 = "50530dfb84fcc9aa7dbe7852e83a37b93b9f2aa6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-arrayish-0.3.2" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz";
        sha512 = "eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==";
      };
    };
    "is-callable-1.2.0" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.0.tgz";
        sha512 = "pyVD9AaGLxtg6srb2Ng6ynWJqkHU9bEM087AKck0w8QwDarTfNcpIYoU8x8Hv2Icm8u6kFJM18Dag8lyqGkviw==";
      };
    };
    "is-color-stop-1.1.0" = {
      name = "is-color-stop";
      packageName = "is-color-stop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-color-stop/-/is-color-stop-1.1.0.tgz";
        sha1 = "cfff471aee4dd5c9e158598fbe12967b5cdad345";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-directory-0.3.1" = {
      name = "is-directory";
      packageName = "is-directory";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-directory/-/is-directory-0.3.1.tgz";
        sha1 = "61339b6f2475fc772fd9c9d83f5c8575dc154ae1";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-regex-1.1.0" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.0.tgz";
        sha512 = "iI97M8KTWID2la5uYXlkbSDQIg4F6o1sYboZKKTDpnDQMLtUL86zxhgDet3Q2SriaYsyGqZ6Mn2SjbRKeLHdqw==";
      };
    };
    "is-resolvable-1.1.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.1.0.tgz";
        sha512 = "qgDYXFSR5WvEfuS5dMj6oTMEbrrSaM0CrFk2Yiq/gXnBvD9pMa2jGXxyhGLfvhZpuMZe18CJpFxAt3CRs42NMg==";
      };
    };
    "is-svg-3.0.0" = {
      name = "is-svg";
      packageName = "is-svg";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-svg/-/is-svg-3.0.0.tgz";
        sha512 = "gi4iHK53LR2ujhLVVj+37Ykh9GLqYHX6JOVXbLAucaG/Cqw9xwdFOjDM2qeifLs1sF1npXXFvDu0r5HNgCMrzQ==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "jquery-3.5.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.5.1.tgz";
        sha512 = "XwIBPqcMn57FxfT+Go5pzySnm4KWkT1Tv7gjrpT1srtf8Weynl6R273VJ5GjkRb51IzMp5nbaPjJXMWeju2MKg==";
      };
    };
    "js-yaml-3.14.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.0.tgz";
        sha512 = "/4IbIeHcD9VMHFqDR/gQ7EdZdLimOvW2DdcxFjdyyZ9NsbS+ccrXqVWDtab/lRl5AlUqmpBx8EhPaWR+OtY17A==";
      };
    };
    "jsesc-0.5.0" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-0.5.0.tgz";
        sha1 = "e7dee66e35d6fc16f710fe91d5cf69f70f08911d";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "json5-1.0.1" = {
      name = "json5";
      packageName = "json5";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-1.0.1.tgz";
        sha512 = "aKS4WQjPenRxiQsC93MNfjx+nbF4PAdYzmd/1JIj8HYzqfbu86beTuNgXDzPknWk0n0uARlyewZo4s++ES36Ow==";
      };
    };
    "kleur-3.0.3" = {
      name = "kleur";
      packageName = "kleur";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-3.0.3.tgz";
        sha512 = "eTIzlVOSUR+JxdDFepEYcBMtZ9Qqdef+rnzWdRZuMbOywu5tO2w2N7rqjoANZ5k9vywhL6Br1VRjUIgTQx4E8w==";
      };
    };
    "loader-utils-1.4.0" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-1.4.0.tgz";
        sha512 = "qH0WSMBtn/oHuwjy/NucEgbx5dbxxnxup9s4PVXJUDHZBQY+s0NWA9rJf53RBnQZxfch7euUui7hpoAPvALZdA==";
      };
    };
    "local-access-1.0.1" = {
      name = "local-access";
      packageName = "local-access";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/local-access/-/local-access-1.0.1.tgz";
        sha512 = "ykt2pgN0aqIy6KQC1CqdWTWkmUwNgaOS6dcpHVjyBJONA+Xi7AtSB1vuxC/U/0tjIP3wcRudwQk1YYzUvzk2bA==";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "lodash.camelcase-4.3.0" = {
      name = "lodash.camelcase";
      packageName = "lodash.camelcase";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.camelcase/-/lodash.camelcase-4.3.0.tgz";
        sha1 = "b28aa6288a2b9fc651035c7711f65ab6190331a6";
      };
    };
    "lodash.memoize-4.1.2" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-4.1.2.tgz";
        sha1 = "bcc6c49a42a2840ed997f323eada5ecd182e0bfe";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha1 = "d0225373aeb652adc1bc82e4945339a842754773";
      };
    };
    "mdn-data-2.0.4" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.4.tgz";
        sha512 = "iV3XNKw06j5Q7mi6h+9vbx23Tv7JkjEVgKHW4pimwyDGWm0OIQntJJ+u1C6mg6mK1EaTv42XQ7w76yuzH7M2cA==";
      };
    };
    "mdn-data-2.0.6" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.6.tgz";
        sha512 = "rQvjv71olwNHgiTbfPZFkJtjNMciWgswYeciZhtvWLO8bmX3TnhyA62I6sTWOyZssWHJJjY6/KiWwqQsWWsqOA==";
      };
    };
    "mime-2.4.6" = {
      name = "mime";
      packageName = "mime";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.4.6.tgz";
        sha512 = "RZKhC3EmpBchfTGBVb8fb+RL2cWyw/32lshnsETttkBAyAUXSGHxbEJWWRXc751DrIxG1q04b8QwMbAwkRPpUA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "mri-1.1.5" = {
      name = "mri";
      packageName = "mri";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mri/-/mri-1.1.5.tgz";
        sha512 = "d2RKzMD4JNyHMbnbWnznPaa8vbdlq/4pNZ3IgdaGrVbBhebBsGUUE/6qorTMYNS6TwuH3ilfOlD2bf4Igh8CKg==";
      };
    };
    "node-releases-1.1.58" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "1.1.58";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-1.1.58.tgz";
        sha512 = "NxBudgVKiRh/2aPWMgPR7bPTX0VPmGx5QBwCtdHitnqFE5/O8DeBXuIMH1nwNnw/aMo6AjOrpsHzfY3UbUJ7yg==";
      };
    };
    "normalize-url-3.3.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-3.3.0.tgz";
        sha512 = "U+JJi7duF1o+u2pynbp2zXDW2/PADgC30f0GsHZtRh+HOcXHnw137TrNlyxxRvWW5fjKd3bcLHPxofWuCjaeZg==";
      };
    };
    "nth-check-1.0.2" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz";
        sha512 = "WeBOdju8SnzPN5vTUJYxYUxLeXpCaVP5i5e0LF8fg7WORF2Wd7wFX/pk0tYZk7s8T+J7VLy0Da6J1+wCT0AtHg==";
      };
    };
    "object-inspect-1.7.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.7.0.tgz";
        sha512 = "a7pEHdh1xKIAgTySUGgLMx/xwDZskN1Ud6egYYN3EdRW4ZMPNEDUTF+hwy2LUC+Bl+SyLXANnwz/jyh/qutKUw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "object.getownpropertydescriptors-2.1.0" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.0.tgz";
        sha512 = "Z53Oah9A3TdLoblT7VKJaTDdXdT+lQO+cNpKVnya5JDe9uLvzu1YyY1yFDFrcxrlRgWrEFH0jJtD/IbuwjcEVg==";
      };
    };
    "object.values-1.1.1" = {
      name = "object.values";
      packageName = "object.values";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.values/-/object.values-1.1.1.tgz";
        sha512 = "WTa54g2K8iu0kmS/us18jEmdv1a4Wi//BZ/DTVYEcH0XhLM5NYdpDHja3gt57VrZLcNAO2WGA+KpWsDBaHt6eA==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-queue-6.4.0" = {
      name = "p-queue";
      packageName = "p-queue";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-queue/-/p-queue-6.4.0.tgz";
        sha512 = "X7ddxxiQ+bLR/CUt3/BVKrGcJDNxBr0pEEFKHHB6vTPWNUhgDv36GpIH18RmGM3YGPpBT+JWGjDDqsVGuF0ERw==";
      };
    };
    "p-timeout-3.2.0" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-3.2.0.tgz";
        sha512 = "rhIwUycgwwKcP9yTOOFK/AKsAopjjCakVqLHePO3CC6Mir1Z99xT+R63jZxAT5lFZLa2inS5h+ZS2GvR99/FBg==";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "parse-json-4.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-4.0.0.tgz";
        sha1 = "be35f5425be1f7f6c747184f98a788cb99477ee0";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "pify-5.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-5.0.0.tgz";
        sha512 = "eW/gHNMlxdSP6dmG6uJip6FXN0EQBwm2clYYd8Wul42Cwu/DK8HEftzsapcNdYe2MfLiIwZqsDk2RDEsTE79hA==";
      };
    };
    "pkg-up-2.0.0" = {
      name = "pkg-up";
      packageName = "pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkg-up/-/pkg-up-2.0.0.tgz";
        sha1 = "c819ac728059a461cab1c3889a2be3c49a004d7f";
      };
    };
    "popper.js-1.16.1" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.16.1.tgz";
        sha512 = "Wb4p1J4zyFTbM+u6WuO4XstYx4Ky9Cewe4DWrel7B0w6VVICvPwdOpotjzcf6eD8TsckVnIMNONQyPIUFOUbCQ==";
      };
    };
    "postcss-6.0.1" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.1.tgz";
        sha1 = "000dbd1f8eef217aa368b9a212c5fc40b2a8f3f2";
      };
    };
    "postcss-6.0.23" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.23.tgz";
        sha512 = "soOk1h6J3VMTZtVeVpv15/Hpdl2cBLX3CAw4TAbkpTJiNPk9YP/zWcD1ND+xEtvyuuvKzbxliTOIyvkSeSJ6ag==";
      };
    };
    "postcss-7.0.32" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.32.tgz";
        sha512 = "03eXong5NLnNCD05xscnGKGDZ98CyzoqPSMjOe6SuoQY7Z2hIj0Ld1g/O/UQRuOle2aRtiIRDg9tDcTGAkLfKw==";
      };
    };
    "postcss-calc-7.0.2" = {
      name = "postcss-calc";
      packageName = "postcss-calc";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-calc/-/postcss-calc-7.0.2.tgz";
        sha512 = "rofZFHUg6ZIrvRwPeFktv06GdbDYLcGqh9EwiMutZg+a0oePCCw1zHOEiji6LCpyRcjTREtPASuUqeAvYlEVvQ==";
      };
    };
    "postcss-colormin-4.0.3" = {
      name = "postcss-colormin";
      packageName = "postcss-colormin";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-colormin/-/postcss-colormin-4.0.3.tgz";
        sha512 = "WyQFAdDZpExQh32j0U0feWisZ0dmOtPl44qYmJKkq9xFWY3p+4qnRzCHeNrkeRhwPHz9bQ3mo0/yVkaply0MNw==";
      };
    };
    "postcss-convert-values-4.0.1" = {
      name = "postcss-convert-values";
      packageName = "postcss-convert-values";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-4.0.1.tgz";
        sha512 = "Kisdo1y77KUC0Jmn0OXU/COOJbzM8cImvw1ZFsBgBgMgb1iL23Zs/LXRe3r+EZqM3vGYKdQ2YJVQ5VkJI+zEJQ==";
      };
    };
    "postcss-discard-comments-4.0.2" = {
      name = "postcss-discard-comments";
      packageName = "postcss-discard-comments";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-4.0.2.tgz";
        sha512 = "RJutN259iuRf3IW7GZyLM5Sw4GLTOH8FmsXBnv8Ab/Tc2k4SR4qbV4DNbyyY4+Sjo362SyDmW2DQ7lBSChrpkg==";
      };
    };
    "postcss-discard-duplicates-4.0.2" = {
      name = "postcss-discard-duplicates";
      packageName = "postcss-discard-duplicates";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-4.0.2.tgz";
        sha512 = "ZNQfR1gPNAiXZhgENFfEglF93pciw0WxMkJeVmw8eF+JZBbMD7jp6C67GqJAXVZP2BWbOztKfbsdmMp/k8c6oQ==";
      };
    };
    "postcss-discard-empty-4.0.1" = {
      name = "postcss-discard-empty";
      packageName = "postcss-discard-empty";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-4.0.1.tgz";
        sha512 = "B9miTzbznhDjTfjvipfHoqbWKwd0Mj+/fL5s1QOz06wufguil+Xheo4XpOnc4NqKYBCNqqEzgPv2aPBIJLox0w==";
      };
    };
    "postcss-discard-overridden-4.0.1" = {
      name = "postcss-discard-overridden";
      packageName = "postcss-discard-overridden";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-overridden/-/postcss-discard-overridden-4.0.1.tgz";
        sha512 = "IYY2bEDD7g1XM1IDEsUT4//iEYCxAmP5oDSFMVU/JVvT7gh+l4fmjciLqGgwjdWpQIdb0Che2VX00QObS5+cTg==";
      };
    };
    "postcss-load-config-2.1.0" = {
      name = "postcss-load-config";
      packageName = "postcss-load-config";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-config/-/postcss-load-config-2.1.0.tgz";
        sha512 = "4pV3JJVPLd5+RueiVVB+gFOAa7GWc25XQcMp86Zexzke69mKf6Nx9LRcQywdz7yZI9n1udOxmLuAwTBypypF8Q==";
      };
    };
    "postcss-merge-longhand-4.0.11" = {
      name = "postcss-merge-longhand";
      packageName = "postcss-merge-longhand";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-4.0.11.tgz";
        sha512 = "alx/zmoeXvJjp7L4mxEMjh8lxVlDFX1gqWHzaaQewwMZiVhLo42TEClKaeHbRf6J7j82ZOdTJ808RtN0ZOZwvw==";
      };
    };
    "postcss-merge-rules-4.0.3" = {
      name = "postcss-merge-rules";
      packageName = "postcss-merge-rules";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-4.0.3.tgz";
        sha512 = "U7e3r1SbvYzO0Jr3UT/zKBVgYYyhAz0aitvGIYOYK5CPmkNih+WDSsS5tvPrJ8YMQYlEMvsZIiqmn7HdFUaeEQ==";
      };
    };
    "postcss-minify-font-values-4.0.2" = {
      name = "postcss-minify-font-values";
      packageName = "postcss-minify-font-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-font-values/-/postcss-minify-font-values-4.0.2.tgz";
        sha512 = "j85oO6OnRU9zPf04+PZv1LYIYOprWm6IA6zkXkrJXyRveDEuQggG6tvoy8ir8ZwjLxLuGfNkCZEQG7zan+Hbtg==";
      };
    };
    "postcss-minify-gradients-4.0.2" = {
      name = "postcss-minify-gradients";
      packageName = "postcss-minify-gradients";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-4.0.2.tgz";
        sha512 = "qKPfwlONdcf/AndP1U8SJ/uzIJtowHlMaSioKzebAXSG4iJthlWC9iSWznQcX4f66gIWX44RSA841HTHj3wK+Q==";
      };
    };
    "postcss-minify-params-4.0.2" = {
      name = "postcss-minify-params";
      packageName = "postcss-minify-params";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-4.0.2.tgz";
        sha512 = "G7eWyzEx0xL4/wiBBJxJOz48zAKV2WG3iZOqVhPet/9geefm/Px5uo1fzlHu+DOjT+m0Mmiz3jkQzVHe6wxAWg==";
      };
    };
    "postcss-minify-selectors-4.0.2" = {
      name = "postcss-minify-selectors";
      packageName = "postcss-minify-selectors";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-4.0.2.tgz";
        sha512 = "D5S1iViljXBj9kflQo4YutWnJmwm8VvIsU1GeXJGiG9j8CIg9zs4voPMdQDUmIxetUOh60VilsNzCiAFTOqu3g==";
      };
    };
    "postcss-modules-2.0.0" = {
      name = "postcss-modules";
      packageName = "postcss-modules";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules/-/postcss-modules-2.0.0.tgz";
        sha512 = "eqp+Bva+U2cwQO7dECJ8/V+X+uH1HduNeITB0CPPFAu6d/8LKQ32/j+p9rQ2YL1QytVcrNU0X+fBqgGmQIA1Rw==";
      };
    };
    "postcss-modules-extract-imports-1.1.0" = {
      name = "postcss-modules-extract-imports";
      packageName = "postcss-modules-extract-imports";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-extract-imports/-/postcss-modules-extract-imports-1.1.0.tgz";
        sha1 = "b614c9720be6816eaee35fb3a5faa1dba6a05ddb";
      };
    };
    "postcss-modules-local-by-default-1.2.0" = {
      name = "postcss-modules-local-by-default";
      packageName = "postcss-modules-local-by-default";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-local-by-default/-/postcss-modules-local-by-default-1.2.0.tgz";
        sha1 = "f7d80c398c5a393fa7964466bd19500a7d61c069";
      };
    };
    "postcss-modules-scope-1.1.0" = {
      name = "postcss-modules-scope";
      packageName = "postcss-modules-scope";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-scope/-/postcss-modules-scope-1.1.0.tgz";
        sha1 = "d6ea64994c79f97b62a72b426fbe6056a194bb90";
      };
    };
    "postcss-modules-values-1.3.0" = {
      name = "postcss-modules-values";
      packageName = "postcss-modules-values";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-values/-/postcss-modules-values-1.3.0.tgz";
        sha1 = "ecffa9d7e192518389f42ad0e83f72aec456ea20";
      };
    };
    "postcss-normalize-charset-4.0.1" = {
      name = "postcss-normalize-charset";
      packageName = "postcss-normalize-charset";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-4.0.1.tgz";
        sha512 = "gMXCrrlWh6G27U0hF3vNvR3w8I1s2wOBILvA87iNXaPvSNo5uZAMYsZG7XjCUf1eVxuPfyL4TJ7++SGZLc9A3g==";
      };
    };
    "postcss-normalize-display-values-4.0.2" = {
      name = "postcss-normalize-display-values";
      packageName = "postcss-normalize-display-values";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-display-values/-/postcss-normalize-display-values-4.0.2.tgz";
        sha512 = "3F2jcsaMW7+VtRMAqf/3m4cPFhPD3EFRgNs18u+k3lTJJlVe7d0YPO+bnwqo2xg8YiRpDXJI2u8A0wqJxMsQuQ==";
      };
    };
    "postcss-normalize-positions-4.0.2" = {
      name = "postcss-normalize-positions";
      packageName = "postcss-normalize-positions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-positions/-/postcss-normalize-positions-4.0.2.tgz";
        sha512 = "Dlf3/9AxpxE+NF1fJxYDeggi5WwV35MXGFnnoccP/9qDtFrTArZ0D0R+iKcg5WsUd8nUYMIl8yXDCtcrT8JrdA==";
      };
    };
    "postcss-normalize-repeat-style-4.0.2" = {
      name = "postcss-normalize-repeat-style";
      packageName = "postcss-normalize-repeat-style";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-repeat-style/-/postcss-normalize-repeat-style-4.0.2.tgz";
        sha512 = "qvigdYYMpSuoFs3Is/f5nHdRLJN/ITA7huIoCyqqENJe9PvPmLhNLMu7QTjPdtnVf6OcYYO5SHonx4+fbJE1+Q==";
      };
    };
    "postcss-normalize-string-4.0.2" = {
      name = "postcss-normalize-string";
      packageName = "postcss-normalize-string";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-string/-/postcss-normalize-string-4.0.2.tgz";
        sha512 = "RrERod97Dnwqq49WNz8qo66ps0swYZDSb6rM57kN2J+aoyEAJfZ6bMx0sx/F9TIEX0xthPGCmeyiam/jXif0eA==";
      };
    };
    "postcss-normalize-timing-functions-4.0.2" = {
      name = "postcss-normalize-timing-functions";
      packageName = "postcss-normalize-timing-functions";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-timing-functions/-/postcss-normalize-timing-functions-4.0.2.tgz";
        sha512 = "acwJY95edP762e++00Ehq9L4sZCEcOPyaHwoaFOhIwWCDfik6YvqsYNxckee65JHLKzuNSSmAdxwD2Cud1Z54A==";
      };
    };
    "postcss-normalize-unicode-4.0.1" = {
      name = "postcss-normalize-unicode";
      packageName = "postcss-normalize-unicode";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-unicode/-/postcss-normalize-unicode-4.0.1.tgz";
        sha512 = "od18Uq2wCYn+vZ/qCOeutvHjB5jm57ToxRaMeNuf0nWVHaP9Hua56QyMF6fs/4FSUnVIw0CBPsU0K4LnBPwYwg==";
      };
    };
    "postcss-normalize-url-4.0.1" = {
      name = "postcss-normalize-url";
      packageName = "postcss-normalize-url";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-4.0.1.tgz";
        sha512 = "p5oVaF4+IHwu7VpMan/SSpmpYxcJMtkGppYf0VbdH5B6hN8YNmVyJLuY9FmLQTzY3fag5ESUUHDqM+heid0UVA==";
      };
    };
    "postcss-normalize-whitespace-4.0.2" = {
      name = "postcss-normalize-whitespace";
      packageName = "postcss-normalize-whitespace";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-whitespace/-/postcss-normalize-whitespace-4.0.2.tgz";
        sha512 = "tO8QIgrsI3p95r8fyqKV+ufKlSHh9hMJqACqbv2XknufqEDhDvbguXGBBqxw9nsQoXWf0qOqppziKJKHMD4GtA==";
      };
    };
    "postcss-ordered-values-4.1.2" = {
      name = "postcss-ordered-values";
      packageName = "postcss-ordered-values";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-4.1.2.tgz";
        sha512 = "2fCObh5UanxvSxeXrtLtlwVThBvHn6MQcu4ksNT2tsaV2Fg76R2CV98W7wNSlX+5/pFwEyaDwKLLoEV7uRybAw==";
      };
    };
    "postcss-reduce-initial-4.0.3" = {
      name = "postcss-reduce-initial";
      packageName = "postcss-reduce-initial";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-initial/-/postcss-reduce-initial-4.0.3.tgz";
        sha512 = "gKWmR5aUulSjbzOfD9AlJiHCGH6AEVLaM0AV+aSioxUDd16qXP1PCh8d1/BGVvpdWn8k/HiK7n6TjeoXN1F7DA==";
      };
    };
    "postcss-reduce-transforms-4.0.2" = {
      name = "postcss-reduce-transforms";
      packageName = "postcss-reduce-transforms";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-transforms/-/postcss-reduce-transforms-4.0.2.tgz";
        sha512 = "EEVig1Q2QJ4ELpJXMZR8Vt5DQx8/mo+dGWSR7vWXqcob2gQLyQGsionYcGKATXvQzMPn6DSN1vTN7yFximdIAg==";
      };
    };
    "postcss-selector-parser-3.1.2" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-3.1.2.tgz";
        sha512 = "h7fJ/5uWuRVyOtkO45pnt1Ih40CEleeyCHzipqAZO2e5H20g25Y48uYnFUiShvY4rZWNJ/Bib/KVPmanaCtOhA==";
      };
    };
    "postcss-selector-parser-6.0.2" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.2.tgz";
        sha512 = "36P2QR59jDTOAiIkqEprfJDsoNrvwFei3eCqKd1Y0tUsBimsq39BLp7RD+JWny3WgB1zGhJX8XVePwm9k4wdBg==";
      };
    };
    "postcss-svgo-4.0.2" = {
      name = "postcss-svgo";
      packageName = "postcss-svgo";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-svgo/-/postcss-svgo-4.0.2.tgz";
        sha512 = "C6wyjo3VwFm0QgBy+Fu7gCYOkCmgmClghO+pjcxvrcBKtiKt0uCF+hvbMO1fyv5BMImRK90SMb+dwUnfbGd+jw==";
      };
    };
    "postcss-unique-selectors-4.0.1" = {
      name = "postcss-unique-selectors";
      packageName = "postcss-unique-selectors";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-4.0.1.tgz";
        sha512 = "+JanVaryLo9QwZjKrmJgkI4Fn8SBgRO6WXQBJi7KiAVPlmxikB5Jzc4EvXMT2H0/m0RjrVVm9rGNhZddm/8Spg==";
      };
    };
    "postcss-value-parser-3.3.1" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-3.3.1.tgz";
        sha512 = "pISE66AbVkp4fDQ7VHBwRNXzAAKJjw4Vw7nWI/+Q3vuly7SNfgYXvm6i5IgFylHGK5sP/xHAbB7N49OS4gWNyQ==";
      };
    };
    "postcss-value-parser-4.1.0" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-4.1.0.tgz";
        sha512 = "97DXOFbQJhk71ne5/Mt6cOu6yxsSfM0QGQyl0L25Gca4yGWEGJaig7l7gbCX623VqTBNGLRLaVUCnNkcedlRSQ==";
      };
    };
    "promise.series-0.2.0" = {
      name = "promise.series";
      packageName = "promise.series";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise.series/-/promise.series-0.2.0.tgz";
        sha1 = "2cc7ebe959fc3a6619c04ab4dbdc9e452d864bbd";
      };
    };
    "q-1.5.1" = {
      name = "q";
      packageName = "q";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.1.tgz";
        sha1 = "7e32f75b41381291d04611f1bf14109ac00651d7";
      };
    };
    "regenerate-1.4.1" = {
      name = "regenerate";
      packageName = "regenerate";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerate/-/regenerate-1.4.1.tgz";
        sha512 = "j2+C8+NtXQgEKWk49MMP5P/u2GhnahTtVkRIHr5R5lVRlbKvmQ+oS+A5aLKWp2ma5VkT8sh6v+v4hbH0YHR66A==";
      };
    };
    "regenerate-unicode-properties-8.2.0" = {
      name = "regenerate-unicode-properties";
      packageName = "regenerate-unicode-properties";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerate-unicode-properties/-/regenerate-unicode-properties-8.2.0.tgz";
        sha512 = "F9DjY1vKLo/tPePDycuH3dn9H1OTPIkVD9Kz4LODu+F2C75mgjAJ7x/gwy6ZcSNRAAkhNlJSOHRe8k3p+K9WhA==";
      };
    };
    "regexpu-core-4.7.0" = {
      name = "regexpu-core";
      packageName = "regexpu-core";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpu-core/-/regexpu-core-4.7.0.tgz";
        sha512 = "TQ4KXRnIn6tz6tjnrXEkD/sshygKH/j5KzK86X8MkeHyZ8qst/LZ89j3X4/8HEIfHANTFIP/AbXakeRhWIl5YQ==";
      };
    };
    "regjsgen-0.5.2" = {
      name = "regjsgen";
      packageName = "regjsgen";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsgen/-/regjsgen-0.5.2.tgz";
        sha512 = "OFFT3MfrH90xIW8OOSyUrk6QHD5E9JOTeGodiJeBS3J6IwlgzJMNE/1bZklWz5oTg+9dCMyEetclvCVXOPoN3A==";
      };
    };
    "regjsparser-0.6.4" = {
      name = "regjsparser";
      packageName = "regjsparser";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsparser/-/regjsparser-0.6.4.tgz";
        sha512 = "64O87/dPDgfk8/RQqC4gkZoGyyWFIEUTTh80CU6CWuK5vkCGyekIx+oKcEIYtP/RAxSQltCZHCNu/mdd7fqlJw==";
      };
    };
    "resolve-1.17.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.17.0.tgz";
        sha512 = "ic+7JYiV8Vi2yzQGFWOkiZD5Z9z7O2Zhm9XMaTxdJExKasieFCr+yXZ/WmXsckHiKl12ar0y6XiXDx3m4RHn1w==";
      };
    };
    "resolve-from-3.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-3.0.0.tgz";
        sha1 = "b22c7af7d9d6881bc8b6e653335eebcb0a188748";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "rgb-regex-1.0.1" = {
      name = "rgb-regex";
      packageName = "rgb-regex";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgb-regex/-/rgb-regex-1.0.1.tgz";
        sha1 = "c0e0d6882df0e23be254a475e8edd41915feaeb1";
      };
    };
    "rgba-regex-1.0.0" = {
      name = "rgba-regex";
      packageName = "rgba-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz";
        sha1 = "43374e2e2ca0968b0ef1523460b7d730ff22eeb3";
      };
    };
    "rollup-plugin-postcss-3.1.2" = {
      name = "rollup-plugin-postcss";
      packageName = "rollup-plugin-postcss";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-plugin-postcss/-/rollup-plugin-postcss-3.1.2.tgz";
        sha512 = "29ocL0CqjLj9sUghTG64ZwFxwbo2d0WyOTVtqPg6SEMZyFmKke9TClBf4/CcdFaWHqS+YZGsUpq3mzIBSYrw+A==";
      };
    };
    "rollup-pluginutils-2.8.2" = {
      name = "rollup-pluginutils";
      packageName = "rollup-pluginutils";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-pluginutils/-/rollup-pluginutils-2.8.2.tgz";
        sha512 = "EEp9NhnUkwY8aif6bxgovPHMoMoNr2FulJziTndpt5H9RdwC47GSGuII9XxpSdzVGM0GWrNPHV6ie1LTNJPaLQ==";
      };
    };
    "sade-1.7.3" = {
      name = "sade";
      packageName = "sade";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sade/-/sade-1.7.3.tgz";
        sha512 = "m4BctppMvJ60W1dXnHq7jMmFe3hPJZDAH85kQ3ACTo7XZNVUuTItCQ+2HfyaMeV5cKrbw7l4vD/6We3GBxvdJw==";
      };
    };
    "safe-identifier-0.4.1" = {
      name = "safe-identifier";
      packageName = "safe-identifier";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-identifier/-/safe-identifier-0.4.1.tgz";
        sha512 = "73tOz5TXsq3apuCc3vC8c9QRhhdNZGiBhHmPPjqpH4TO5oCDqk8UIsDcSs/RG6dYcFAkOOva0pqHS3u7hh7XXA==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "simple-swizzle-0.2.2" = {
      name = "simple-swizzle";
      packageName = "simple-swizzle";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz";
        sha1 = "a4da6b635ffcccca33f70d17cb92592de95e557a";
      };
    };
    "sirv-0.4.6" = {
      name = "sirv";
      packageName = "sirv";
      version = "0.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/sirv/-/sirv-0.4.6.tgz";
        sha512 = "rYpOXlNbpHiY4nVXxuDf4mXPvKz1reZGap/LkWp9TvcZ84qD/nPBjjH/6GZsgIjVMbOslnY8YYULAyP8jMn1GQ==";
      };
    };
    "sirv-cli-0.4.6" = {
      name = "sirv-cli";
      packageName = "sirv-cli";
      version = "0.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/sirv-cli/-/sirv-cli-0.4.6.tgz";
        sha512 = "/Vj85/kBvPL+n9ibgX6FicLE8VjidC1BhlX67PYPBfbBAphzR6i0k0HtU5c2arejfU3uzq8l3SYPCwl1x7z6Ww==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stable-0.1.8" = {
      name = "stable";
      packageName = "stable";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz";
        sha512 = "ji9qxRnOVfcuLDySj9qzhGSEFVobyt1kIOSkj1qZzYLzq7Tos/oUUWvotUPQLlrsidqsK6tBH89Bc9kL5zHA6w==";
      };
    };
    "string-hash-1.1.3" = {
      name = "string-hash";
      packageName = "string-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-hash/-/string-hash-1.1.3.tgz";
        sha1 = "e8aafc0ac1855b4666929ed7dd1275df5d6c811b";
      };
    };
    "string.prototype.trimend-1.0.1" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.1.tgz";
        sha512 = "LRPxFUaTtpqYsTeNKaFOw3R4bxIzWOnbQ837QfBylo8jIxtcbK/A/sMV7Q+OAV/vWo+7s25pOE10KYSjaSO06g==";
      };
    };
    "string.prototype.trimstart-1.0.1" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.1.tgz";
        sha512 = "XxZn+QpvrBI1FOcg6dIpxUPgWCPuNXvMD72aaRaUQv1eD4e/Qy8i/hFTe0BUmD60p/QA6bh1avmuPTfNjqVWRw==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "style-inject-0.3.0" = {
      name = "style-inject";
      packageName = "style-inject";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-inject/-/style-inject-0.3.0.tgz";
        sha512 = "IezA2qp+vcdlhJaVm5SOdPPTUu0FCEqfNSli2vRuSIBbu5Nq5UvygTk/VzeCqfLz2Atj3dVII5QBKGZRZ0edzw==";
      };
    };
    "stylehacks-4.0.3" = {
      name = "stylehacks";
      packageName = "stylehacks";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylehacks/-/stylehacks-4.0.3.tgz";
        sha512 = "7GlLk9JwlElY4Y6a/rmbH2MhVlTyVmiJd1PfTCqFaIBEGMYNsrO/v3SeGTdhBThLg4Z+NbOk/qFMwCa+J+3p/g==";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-3.2.3" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-3.2.3.tgz";
        sha1 = "65ac0504b3954171d8a64946b2ae3cbb8a5f54f6";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "supports-color-7.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.1.0.tgz";
        sha512 = "oRSIpR8pxT1Wr2FquTNnGet79b3BWljqOuoW/h4oBhxJ/HUbX5nX6JSruTkvXDCFMwDPvsaTTbvMLKZWSy0R5g==";
      };
    };
    "svgo-1.3.2" = {
      name = "svgo";
      packageName = "svgo";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-1.3.2.tgz";
        sha512 = "yhy/sQYxR5BkC98CY7o31VGsg014AKLEPxdfhora76l36hD9Rdy5NZA/Ocn6yayNPgSamYdtX2rFJdcv07AYVw==";
      };
    };
    "timsort-0.3.0" = {
      name = "timsort";
      packageName = "timsort";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timsort/-/timsort-0.3.0.tgz";
        sha1 = "405411a8e7e6339fe64db9a234de11dc31e02bd4";
      };
    };
    "tinydate-1.2.0" = {
      name = "tinydate";
      packageName = "tinydate";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinydate/-/tinydate-1.2.0.tgz";
        sha512 = "3GwPk8VhDFnUZ2TrgkhXJs6hcMAIIw4x/xkz+ayK6dGoQmp2nUwKzBXK0WnMsqkh6vfUhpqQicQF3rbshfyJkg==";
      };
    };
    "unicode-canonical-property-names-ecmascript-1.0.4" = {
      name = "unicode-canonical-property-names-ecmascript";
      packageName = "unicode-canonical-property-names-ecmascript";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicode-canonical-property-names-ecmascript/-/unicode-canonical-property-names-ecmascript-1.0.4.tgz";
        sha512 = "jDrNnXWHd4oHiTZnx/ZG7gtUTVp+gCcTTKr8L0HjlwphROEW3+Him+IpvC+xcJEFegapiMZyZe02CyuOnRmbnQ==";
      };
    };
    "unicode-match-property-ecmascript-1.0.4" = {
      name = "unicode-match-property-ecmascript";
      packageName = "unicode-match-property-ecmascript";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicode-match-property-ecmascript/-/unicode-match-property-ecmascript-1.0.4.tgz";
        sha512 = "L4Qoh15vTfntsn4P1zqnHulG0LdXgjSO035fEpdtp6YxXhMT51Q6vgM5lYdG/5X3MjS+k/Y9Xw4SFCY9IkR0rg==";
      };
    };
    "unicode-match-property-value-ecmascript-1.2.0" = {
      name = "unicode-match-property-value-ecmascript";
      packageName = "unicode-match-property-value-ecmascript";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicode-match-property-value-ecmascript/-/unicode-match-property-value-ecmascript-1.2.0.tgz";
        sha512 = "wjuQHGQVofmSJv1uVISKLE5zO2rNGzM/KCYZch/QQvez7C1hUhBIuZ701fYXExuufJFMPhv2SyL8CyoIfMLbIQ==";
      };
    };
    "unicode-property-aliases-ecmascript-1.1.0" = {
      name = "unicode-property-aliases-ecmascript";
      packageName = "unicode-property-aliases-ecmascript";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicode-property-aliases-ecmascript/-/unicode-property-aliases-ecmascript-1.1.0.tgz";
        sha512 = "PqSoPh/pWetQ2phoj5RLiaqIk4kCNwoV3CI+LfGmWLKI3rE3kl1h59XpX2BjgDrmbxD9ARtQobPGU1SguCYuQg==";
      };
    };
    "uniq-1.0.1" = {
      name = "uniq";
      packageName = "uniq";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniq/-/uniq-1.0.1.tgz";
        sha1 = "b31c5ae8254844a3a8281541ce2b04b865a734ff";
      };
    };
    "uniqs-2.0.0" = {
      name = "uniqs";
      packageName = "uniqs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz";
        sha1 = "ffede4b36b25290696e6e165d4a59edb998e6b02";
      };
    };
    "unquote-1.1.1" = {
      name = "unquote";
      packageName = "unquote";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unquote/-/unquote-1.1.1.tgz";
        sha1 = "8fded7324ec6e88a0ff8b905e7c098cdc086d544";
      };
    };
    "util.promisify-1.0.1" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.1.tgz";
        sha512 = "g9JpC/3He3bm38zsLupWryXHoEcS22YHthuPQSJdMy6KNrzIRzWqcsHzD/WUnqe45whVou4VIsPew37DoXWNrA==";
      };
    };
    "vendors-1.0.4" = {
      name = "vendors";
      packageName = "vendors";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vendors/-/vendors-1.0.4.tgz";
        sha512 = "/juG65kTL4Cy2su4P8HjtkTxk6VmJDiOPBufWniqQ6wknac6jNiXS9vU+hO3wgusiyqWlzTbVHi0dyJqRONg3w==";
      };
    };
  };
  args = {
    name = "svelte-app";
    packageName = "svelte-app";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@polka/url-0.5.0"
      sources."@types/color-name-1.1.1"
      sources."@types/q-1.5.4"
      sources."alphanum-sort-1.0.2"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."big.js-5.2.2"
      sources."boolbase-1.0.0"
      sources."bootstrap-4.5.0"
      sources."browserslist-4.12.0"
      sources."caller-callsite-2.0.0"
      sources."caller-path-2.0.0"
      sources."callsites-2.0.0"
      sources."caniuse-api-3.0.0"
      sources."caniuse-lite-1.0.30001084"
      sources."chalk-2.4.2"
      sources."coa-2.0.2"
      sources."color-3.1.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."color-string-1.5.3"
      sources."concat-with-sourcemaps-1.1.0"
      sources."console-clear-1.1.1"
      sources."cosmiconfig-5.2.1"
      sources."css-color-names-0.0.4"
      sources."css-declaration-sorter-4.0.1"
      (sources."css-modules-loader-core-1.1.0" // {
        dependencies = [
          sources."ansi-styles-2.2.1"
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."supports-color-2.0.0"
            ];
          })
          sources."has-flag-1.0.0"
          sources."postcss-6.0.1"
          sources."source-map-0.5.7"
          sources."supports-color-3.2.3"
        ];
      })
      sources."css-select-2.1.0"
      sources."css-select-base-adapter-0.1.1"
      sources."css-selector-tokenizer-0.7.2"
      sources."css-tree-1.0.0-alpha.37"
      sources."css-what-3.3.0"
      sources."cssesc-3.0.0"
      sources."cssnano-4.1.10"
      sources."cssnano-preset-default-4.0.7"
      sources."cssnano-util-get-arguments-4.0.0"
      sources."cssnano-util-get-match-4.0.0"
      sources."cssnano-util-raw-cache-4.0.1"
      sources."cssnano-util-same-parent-4.0.1"
      (sources."csso-4.0.3" // {
        dependencies = [
          sources."css-tree-1.0.0-alpha.39"
          sources."mdn-data-2.0.6"
        ];
      })
      sources."define-properties-1.1.3"
      (sources."dom-serializer-0.2.2" // {
        dependencies = [
          sources."domelementtype-2.0.1"
        ];
      })
      sources."domelementtype-1.3.1"
      sources."domutils-1.7.0"
      sources."dot-prop-5.2.0"
      sources."electron-to-chromium-1.3.477"
      sources."emojis-list-3.0.0"
      sources."entities-2.0.3"
      sources."error-ex-1.3.2"
      sources."es-abstract-1.17.6"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."eventemitter3-4.0.4"
      sources."fastparse-1.1.2"
      sources."find-up-2.1.0"
      sources."function-bind-1.1.1"
      sources."generic-names-2.0.1"
      sources."get-port-3.2.0"
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."has-flag-3.0.0"
      sources."has-symbols-1.0.1"
      sources."hex-color-regex-1.1.0"
      sources."hsl-regex-1.0.0"
      sources."hsla-regex-1.0.0"
      sources."html-comment-regex-1.1.2"
      sources."icss-replace-symbols-1.1.0"
      sources."import-cwd-3.0.0"
      sources."import-fresh-2.0.0"
      (sources."import-from-3.0.0" // {
        dependencies = [
          sources."resolve-from-5.0.0"
        ];
      })
      sources."indexes-of-1.0.1"
      sources."is-absolute-url-2.1.0"
      sources."is-arrayish-0.2.1"
      sources."is-callable-1.2.0"
      sources."is-color-stop-1.1.0"
      sources."is-date-object-1.0.2"
      sources."is-directory-0.3.1"
      sources."is-obj-2.0.0"
      sources."is-regex-1.1.0"
      sources."is-resolvable-1.1.0"
      sources."is-svg-3.0.0"
      sources."is-symbol-1.0.3"
      sources."jquery-3.5.1"
      sources."js-yaml-3.14.0"
      sources."jsesc-0.5.0"
      sources."json-parse-better-errors-1.0.2"
      sources."json5-1.0.1"
      sources."kleur-3.0.3"
      sources."loader-utils-1.4.0"
      sources."local-access-1.0.1"
      sources."locate-path-2.0.0"
      sources."lodash.camelcase-4.3.0"
      sources."lodash.memoize-4.1.2"
      sources."lodash.uniq-4.5.0"
      sources."mdn-data-2.0.4"
      sources."mime-2.4.6"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."mri-1.1.5"
      sources."node-releases-1.1.58"
      sources."normalize-url-3.3.0"
      sources."nth-check-1.0.2"
      sources."object-inspect-1.7.0"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."object.getownpropertydescriptors-2.1.0"
      sources."object.values-1.1.1"
      sources."p-finally-1.0.0"
      sources."p-limit-1.3.0"
      sources."p-locate-2.0.0"
      sources."p-queue-6.4.0"
      sources."p-timeout-3.2.0"
      sources."p-try-1.0.0"
      sources."parse-json-4.0.0"
      sources."path-exists-3.0.0"
      sources."path-parse-1.0.6"
      sources."pify-5.0.0"
      sources."pkg-up-2.0.0"
      sources."popper.js-1.16.1"
      (sources."postcss-7.0.32" // {
        dependencies = [
          sources."supports-color-6.1.0"
        ];
      })
      sources."postcss-calc-7.0.2"
      (sources."postcss-colormin-4.0.3" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-convert-values-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-discard-comments-4.0.2"
      sources."postcss-discard-duplicates-4.0.2"
      sources."postcss-discard-empty-4.0.1"
      sources."postcss-discard-overridden-4.0.1"
      (sources."postcss-load-config-2.1.0" // {
        dependencies = [
          sources."import-cwd-2.1.0"
          sources."import-from-2.1.0"
        ];
      })
      (sources."postcss-merge-longhand-4.0.11" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-merge-rules-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      (sources."postcss-minify-font-values-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-gradients-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-params-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-minify-selectors-4.0.2" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      sources."postcss-modules-2.0.0"
      (sources."postcss-modules-extract-imports-1.1.0" // {
        dependencies = [
          sources."postcss-6.0.23"
        ];
      })
      (sources."postcss-modules-local-by-default-1.2.0" // {
        dependencies = [
          sources."postcss-6.0.23"
        ];
      })
      (sources."postcss-modules-scope-1.1.0" // {
        dependencies = [
          sources."postcss-6.0.23"
        ];
      })
      (sources."postcss-modules-values-1.3.0" // {
        dependencies = [
          sources."postcss-6.0.23"
        ];
      })
      sources."postcss-normalize-charset-4.0.1"
      (sources."postcss-normalize-display-values-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-positions-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-repeat-style-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-string-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-timing-functions-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-unicode-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-url-4.0.1" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-normalize-whitespace-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      (sources."postcss-ordered-values-4.1.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-reduce-initial-4.0.3"
      (sources."postcss-reduce-transforms-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-selector-parser-6.0.2"
      (sources."postcss-svgo-4.0.2" // {
        dependencies = [
          sources."postcss-value-parser-3.3.1"
        ];
      })
      sources."postcss-unique-selectors-4.0.1"
      sources."postcss-value-parser-4.1.0"
      sources."promise.series-0.2.0"
      sources."q-1.5.1"
      sources."regenerate-1.4.1"
      sources."regenerate-unicode-properties-8.2.0"
      sources."regexpu-core-4.7.0"
      sources."regjsgen-0.5.2"
      sources."regjsparser-0.6.4"
      sources."resolve-1.17.0"
      sources."resolve-from-3.0.0"
      sources."rgb-regex-1.0.1"
      sources."rgba-regex-1.0.0"
      (sources."rollup-plugin-postcss-3.1.2" // {
        dependencies = [
          sources."ansi-styles-4.2.1"
          sources."chalk-4.1.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.1.0"
        ];
      })
      (sources."rollup-pluginutils-2.8.2" // {
        dependencies = [
          sources."estree-walker-0.6.1"
        ];
      })
      sources."sade-1.7.3"
      sources."safe-identifier-0.4.1"
      sources."sax-1.2.4"
      (sources."simple-swizzle-0.2.2" // {
        dependencies = [
          sources."is-arrayish-0.3.2"
        ];
      })
      sources."sirv-0.4.6"
      sources."sirv-cli-0.4.6"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."stable-0.1.8"
      sources."string-hash-1.1.3"
      sources."string.prototype.trimend-1.0.1"
      sources."string.prototype.trimstart-1.0.1"
      sources."strip-ansi-3.0.1"
      sources."style-inject-0.3.0"
      (sources."stylehacks-4.0.3" // {
        dependencies = [
          sources."postcss-selector-parser-3.1.2"
        ];
      })
      sources."supports-color-5.5.0"
      sources."svgo-1.3.2"
      sources."timsort-0.3.0"
      sources."tinydate-1.2.0"
      sources."unicode-canonical-property-names-ecmascript-1.0.4"
      sources."unicode-match-property-ecmascript-1.0.4"
      sources."unicode-match-property-value-ecmascript-1.2.0"
      sources."unicode-property-aliases-ecmascript-1.1.0"
      sources."uniq-1.0.1"
      sources."uniqs-2.0.0"
      sources."unquote-1.1.1"
      sources."util.promisify-1.0.1"
      sources."vendors-1.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
